### ISSUE TITLE
UnexpectedParameter: Unexpected key 'SSEDescription' found in params

### ISSUE THREAD

**Issue by praneetnadkar** [mifi/dynamodump#19]
Getting an error on schema import:

`UnexpectedParameter: Unexpected key 'SSEDescription' found in params`

![image](https://user-images.githubusercontent.com/7333796/76192516-ff8dd600-6207-11ea-9604-49cd9191248a.png)

**Comment by mifi** [comment]
Does it work if you delete it?

**Comment by dfejgelis** [comment]
Had the same issue, deleted the `SSEDescription` in the schema and everything worked.

```
  "SSEDescription": {
    "Status": "ENABLED",
    "SSEType": "KMS",
    "KMSMasterKeyArn": "arn:aws:kms:us-east-1:******:key/******"
  },
```

**Comment by mifi** [comment]
then i think the solution should be #30 ?
