### ISSUE TITLE
Sync/merge import instead of wipe + full write

### ISSUE THREAD

**Issue by Lusitaniae** [mifi/dynamodump#23]
I have a dynamo database with over 100k items.

Wiping and fully writing to this database every time comes with a ~ 10$ cost (per time)

If I was doing this every day, would cost 3000$

Having an extra option to sync results (insert/update/delete to synchronize with the exporting node data) would be greatly beneficial.

**Comment by mifi** [comment]
You mean differential export/import, right?

**Comment by Lusitaniae** [comment]
If that's how it's called, I suppose so :+1:

**Comment by mifi** [comment]
You mean when importing data, e.g. 100k rows, do this:
For each row to be imported, first check the database if the row already exists, and if it is the same as the one we are inserting, then don't write it

Because reading rows is much cheaper than writing, right?

**Comment by Lusitaniae** [comment]
Yessir, correct

But as mentioned above, the "Restore Table" feature in AWS itself is probably the right solution (scanning the whole table also adds up a lot of time and may require scaling up/down when on provisioned capacity)

**Comment by mifi** [comment]
I think there is nothing dynamodump can do then, because Restore Table is a completely different thing available from the AWS console?

**Comment by Lusitaniae** [comment]
Guess so!

Could be mentioned in the readme though

**Comment by mifi** [comment]
You want to make a PR? :)
