### ISSUE TITLE
Scaling throughput on export schema fails on import

### ISSUE THREAD

**Issue by ktwbc** [mifi/dynamodump#9]
If you have an existing table that has autoscaling enabled on DynamoDb, the export file will contain information about that history under the ProvisionedThroughput section when exporting schema, three keys:

        "LastIncreaseDateTime": "2017-11-01T23:35:19.322Z",
        "LastDecreaseDateTime": "2017-11-02T00:47:39.705Z",
        "NumberOfDecreasesToday": 0,

These keys cause an import schema to fail. They can be removed manually in the file by editing it before import so there is a workaround.

**Comment by mifi** [comment]
reopen if still an issue
